name: CD

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Build
        run: make build

      - name: Install gosec
        run: ./scripts/buildprod.sh
            
